name: photostory-dev-api

services:
  mysql:
    image: mysql:8.0.38
    container_name: photostory-dev-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env.dev
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql-dev-data:/var/lib/mysql
    networks:
      - photostory-dev-network

  redis:
    image: redis:7.4.3
    container_name: photostory-dev-redis
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    env_file:
      - .env.dev
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-dev-data:/data
    networks:
      - photostory-dev-network

volumes:
  mysql-dev-data:
  redis-dev-data:

networks:
  photostory-dev-network:
    driver: bridge