spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:photostory}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  docker:
    compose:
      profiles:
        active: dev
      file: docker-compose.dev.yml
      lifecycle-management: start-only

logging:
  pattern:
    # Định dạng log đẹp (Ngày giờ - Level - PID - Thread - Class - Message)
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) %clr(${PID:- }){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} : %m%n"

  level:
    root: INFO # Mặc định các thư viện khác là INFO
    space.photostory: DEBUG # Code của bạn thì hiện DEBUG (nếu cần)

    # QUAN TRỌNG: Dòng này giúp tắt log WARN dư thừa của Spring MVC
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR